---
title: "Получение сведений о системе"
author: "Солдатенкова Ксения БИСО-03-20"
engine: knitr
format: 
    md:
        output-file: README.md
---

# Системы аутентификации и защиты от несанкционированного доступа

## Лабораторная работа №1

## Цель работы

Получить сведения об используемой системе

## Исходные данные

1.  ОС Windows 11
2.  WSL2
3.  Ноутбук HP

## План

1.  Вывести информацию о системе. Выполнить команду uname -r
2.  Вывести информацию о процессоре. Выполнить команду cat /proc/cpuinfo \| grep "model name"
3.  Вывести 30 последних строк логов. Выполнить команду journalctl -q -b \| tail -n 30

## Ход работы

1\.  Выполним команду uname -r для вывода информации о системе

```{bash}
uname -r
```

2\. Выполним команду cat /proc/cpuinfo | grep "model name" для вывода информации о процессоре, строки которой содержат "model name"

```{bash}
cat /proc/cpuinfo | grep "model name"
```

3\. Позже выполним команду dmesg | tail -n 30 для вывода последних 30 строк логов.

```{bash}
dmesg | tail -n 30
```
## Оценка результата

В результате данной лабораторной работы мы получили основную информацию об ОС и процессоре, а также логи системы.

## Выводы

Кроме того мы научились работать с базовыми командами Linux и получать информацию об операционной системе.