---
title: "Применение средств и методов OSINT"
author: Солдатенкова Ксения
format: 
    md:
        output-file: README.md
engine: knitr
---

Open source intelligence (OSINT) – разведывательная дисциплина, включающая в себя поиск, выбор
и сбор разведывательной информации из общедоступных источников, а также её анализ.

Такими источниками информации могут быть:

- поисковые машины – Google, Bing, Yandex...

- специализированные поисковые системы – intelx.io, Shodan, Censys...

- порталы открытых данных – Github Awesome Lists, https://opendata.digital.gov.ru/

- материалы профильных конференций

- социальные сети, профильные блоги и т.д.

- официальные сайты компаний

## Цель работы

1. Освоить базовые подходы процессов OSINT

2. Освоить современные инструменты поиска и сбора информации

3. Освоить инструменты совместной работы в ходе аналитической деятельности

## Задание

1. Собрать информацию о компании Газинформcервис и её продуктах

2. Собрать информацию об основных специализированных технологиях, применяемых в средствах защиты информации.

3. Собрать информацию о публичных сотрудниках, ведущих профильные технологические блоги, профили в социальных сетях и т.д.

4. Сформировать представление о рынке отечественных решений ИБ

## Ход выполнения работы

### 1. Полное название компании

Полное юридическое наименование:	ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ГАЗИНФОРМСЕРВИС"

[Источник](https://www.list-org.com/company/576457)

### 2. Структура компании

ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ГАЗИНФОРМСЕРВИС" имеет 8 филиалов и представительств:

Головное подразделение ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ГАЗИНФОРМСЕРВИС"
Адрес: 198096, Санкт-Петербург Город, Улица Кронштадтская, Дом 10, Литера А
ОКПО: 72410666400001 ОКАТО: 40276000000 ОКТМО: 40338000000 ОКОПФ: 30004

ТОСП в г.Воронеж ООО "Газинформсервис"
Адрес: 394000, Воронежская Область, Г Воронеж, Отсутствует
ОКПО: 72410666200002 ОКАТО: 20401000000 ОКТМО: 20701000001 ОКОПФ: 30004

ТЕРРИТОРИАЛЬНО-ОБОСОБЛЕННОЕ СТРУКТУРНОЕ ПОДРАЗДЕЛЕНИЕ В ГОРОДЕ САМАРА ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ГАЗИНФОРМСЕРВИС"
Адрес: 443068, Самарская Область, Г Самара, Ул Конноармейская, Д 17
ОКПО: 72410666360002 ОКАТО: 36401385000 ОКТМО: 36701330000 ОКОПФ: 30004

ФЛ ООО "ГАЗИНФОРМСЕРВИС" в г.Москва
Адрес: 117420, Москва, Ул Наметкина, 16
ОКПО: 72410666400002 ОКАТО: 45293554000 ОКТМО: 45397000000 ОКОПФ: 30004

ФЛ ООО "ГАЗИНФОРМСЕРВИС" г Новый Уренгой
Адрес: 629300, Ямало-Ненецкий Автономный Округ, Г Новый Уренгой, Западная Промзона, Панель "Ж"
ОКПО: 72410666400003 ОКАТО: 71176000000 ОКТМО: 71956000001 ОКОПФ: 30004

Территориально обособленное структурное подразделение ОБЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ГАЗИНФОРМСЕРВИС"
Адрес: 450071, Республика Башкортостан, Г Уфа, Ул Ростовская,3
ОКПО: 72410666400004 ОКАТО: 80401384000 ОКТМО: 80701000001 ОКОПФ: 30004

ОБОСОБЛЕННОЕ ПОДРАЗДЕЛЕНИЕ ОБЩЕСТВА С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ "ГАЗИНФОРМСЕРВИС" В ГОРОДЕ ОМСКЕ
Адрес: 644024, Омская Обл, Г Омск, Ул. Декабристов,45
ОКПО: 72410666520002 ОКАТО: 52401382000 ОКТМО: 52701000001 ОКОПФ: 30003

ФЛ ООО "ГАЗИНФОРМСЕРВИС" в г.Ухта
Адрес: 169309, Республика Коми, Г Ухта, Ул Советская, Д 3
ОКПО: 72410666870002 ОКАТО: 87425000000 ОКТМО: 87725000001 ОКОПФ: 30004

[Источник](https://e-ecolog.ru/entity/7838017968/filial)

### Основные направления деятельности компании

#### Услуги

Аттестация объектов информатизации
Техническая поддержка
Консалтинг в области ИБ
Тестирование на проникновение
Инженерно-технические средства охраны
Сертификация средств защиты информации
Аккредитованный удостоверяющий центр
Доверенная третья сторона (ДТС)

[Источник](https://www.gaz-is.ru/)

#### Производимые продукты, основные сферы их применения, их достоинства

SafeERP
Программное средство SafeERP предназначено для решения задач информационной безопасности, касающихся защиты информационных систем. Программные решения средств защиты информации наиболее актуальны для компаний, использующих информационные системы как программное обеспечение для реализации своих бизнес-стратегий.

Efros Config Inspector
Контроль конфигураций и состояний рабочей среды сетевого оборудования, средств защиты информации, платформ виртуализации и операционных систем.

Efros Access Control Server
Efros Access Control Server обеспечивает централизованную сетевую идентификацию и управление доступом администраторов на всех сетевых устройствах. Объединяет в себе механизмы аутентификации, авторизации и аудита действий пользователей.

Блокхост-Сеть 4
«Блокхост-Сеть 4» - средство контроля съёмных машинных носителей информации и защиты от несанкционированного доступа ресурсов рабочих станций и серверов.

SafeNode System Loader
Средство доверенной загрузки «SafeNode System Loader» (СДЗ) представляет собой программно-техническое средство, встраиваемое в UEFI BIOS, обеспечивающее защиту от несанкционированного доступа к рабочим станциям и серверам с момента их включения до момента старта операционной системы.

АСЗП
Комплексное решение для автоматизации пропускного режима на объектах любого масштаба.

Monitor3S
Спутниковый мониторинг на базе технологий ГЛОНАСС/GPS
Повысьте безопасность и эффективность использования автотранспорта на 30%.

СУБД «Jatoba»
СУБД Jatoba — ПО общего назначения, предназначенное для создания и управления реляционными базами данных. СУБД Jatoba обеспечивает многопользовательский доступ к расположенным в ней данным с разным уровнем конфиденциальности.

Программный комплекс «Litoria Desktop 2»
Программный комплекс «Litoria Desktop 2» предоставляет пользователю возможность полного отказа от бумажного документооборота и перехода к электронному юридически значимому и конфиденциальному взаимодействию (корпоративному, межкорпоративному, трансграничному).

Litoria Crypto Platform
Криптографическая платформа Litoria Crypto Platform позволяет реализовать в эксплуатируемом или разрабатываемом программном обеспечении весь спектр функциональных возможностей инфраструктуры открытых ключей (от формирования электронной подписи и шифрования данных до функций доверенной третьей стороны и архивного штампа времени).

Программно-аппаратный комплекс «Служба доверенной третьей стороны «Litoria DVCS»
Программный комплекс (ПК) «Службы доверенной третьей стороны (СДТС) «Litoria DVCS» - комплекс, обеспечивающий гарантии неприкосновенности и неизменности электронного документа в процессе передачи по государственным и иностранным открытым телекоммуникационным каналам.

Ankey IDM
Программный продукт для централизованного управления учетными записями пользователей и их полномочиями в корпоративных информационных системах, включающий лучшие решения IGA (Identity Governance and Administration).

Ankey SIEM
Система для централизованного управления безопасностью, событиями и информацией. Эффективно и оперативно решает задачу выявления атак и инцидентов, анализирует и управляет событиями информационной безопасности всей IT-инфраструктуры.

Ankey ASAP
Расширенная аналитика событий безопасности c функциями поведенческого анализа.

[Источник](https://www.gaz-is.ru/)

#### Используемые технологии, языки программирования

PostgreSQL СУБД, SAP NetWeaver, ABAP, UEFI BIOS, ГЛОНАСС/GPS, IGA (Identity Governance and Administration), SIEM, DLP, Antivirus, MS Active Directory, системы HRM

[Источник](https://www.ocs.ru/vendors/gazinformservis/)

### 4. Основные клиенты компании

Основными заказчиками являются корпорации энергетической отрасли, промышленные предприятия, органы государственной власти, а также учреждения финансового и телекоммуникационного сектора:
ЧОУ «Газпром школа Санкт-Петербург», ООО «ИБС Экспертиза», ООО «Газпром телеком», ООО «Газпром 335», ООО «Газпром нефтехим Салават», Республиканское унитарное предприятие «Национальный центр электронных услуг», ООО «Газпром экспорт», ООО «Газпромнефть-Хантос», ООО «Газпром телеком», ООО «Газпром добыча Надым», АО «Центральный научно-исследовательский институт автоматики и гидравлики», Служба государственного строительного надзора и экспертизы Санкт-Петербурга, АО «НПО «Высокоточные комплексы», ООО «Газпром трансгаз Самара», Российский морской регистр судоходства, АО «ЦНИИАГ», ООО «Газпром трансгаз Санкт-Петербург», ООО «Новоуренгойский газохимический комплекс», ООО «Газпром трансгаз Ухта», ООО «Газпром трансгаз Ставрополь», ООО «Газпром добыча Ноябрьск», ООО «Газпром трансгаз Краснодар», ООО «Валио», ООО «Газпром газомоторное топливо», ООО «Газпром энерго»

[Источник](https://www.gaz-is.ru/o-kompanii/otzyvy.html?start=30)

### 5. Основные веб-сайты компании и ее продуктов

Основной веб-сайт - https://www.gaz-is.ru/

### 6. Публичные сотрудники компании, активные участники ИТ и ИБ-сообщества, участники профильных конференций, Twitter, Mastodon, Телеграмм-каналов и т.д.

Сергей Полунин - руководитель группы защиты инфраструктурных IT компании «Газинформсервис»
Дмитрий Овчинников - главный специалист группы архитектурных решений защиты ИТ-инфраструктуры
Канал на RuTube: https://rutube.ru/channel/24959395/

### 7. Уникальные достижения, ключевые продукты компании

Компания стала лауреатом премии «PKI-Форума» 2021 в номинации «Проект года» за реализацию трансграничного электронного документооборота.

За 2020 год компания расширила линейку продуктов собственной разработки:

1. На замену более ранней версии продукта «Блокхост-Сеть 2» выпущен «Блокхост-Сеть 3» — средство защиты от несанкционированного доступа, предназначенное для контроля и разграничения доступа к ресурсам рабочих станций и серверов.
2. Запущен облачный сервис программного комплекса спутникового мониторинга Monitor3S. Облачное решение избавит пользователей от содержания и администрирования серверов системы, проблем с хранением больших объёмов данных и круглосуточным поддержанием работоспособности ПО.
3. Выпущено четвертое поколение ПК Efros Config Inspector, предназначенного для контроля конфигураций и состояний рабочей среды сетевого оборудования, средств защиты информации, платформ виртуализации и операционных систем.

Ключевые продукты:
СУБД Jatoba, Блокхост-Сеть 4, Ankey ASAP

[Источник](https://www.gaz-is.ru/o-kompanii/otzyvy.html?start=30)

## Выводы

Таким образом, с помощью процесса OSINT была получена информация о компании Газинформсервис.